---
title: "Comparing Datasets"
author: "Sofia Bliss-Carrascosa"
date: "9/12/2022"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
```{r load packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
```

V2: TESTING THE R-VERSION COMPARED TO ORIGINAL VERSION
Loading R-version

```{r v0 all unsorted, message=FALSE, warning=FALSE}
v0_all_us_unsorted <- read_csv("allUS_unsorted.csv")
```

```{r load og v1, warning=FALSE, message=FALSE}
v1_all_us_polclaims <- read_csv("all_us_pol_claims_updated_sep15.csv")
```

```{r create r v2, warning=FALSE, message=FALSE}
v2_5parties <- v1_all_us_polclaims %>%
  filter(claimant_party == "Republican"|
           claimant_party == "Democratic"| 
         claimant_party == "Independent"|
         claimant_party == "Libertarian"| 
         claimant_party == "unknown_affiliation")

v2_5parties %>%
  count(publisher.site) %>%
  kable(caption = "All Claims in 5 Parties
        Sorted by Publisher")

dim(v2_5parties)
```

Loading Grace Original Version

```{r load grace v2, warning=FALSE, message=FALSE}
grace_v2 <- read_csv("grace_v2_CSVversion.csv")

grace_v2 %>%
  count(publisher.site) %>%
  kable(caption = "All Claims in 5 Parties
        Sorted by Publisher")

dim(grace_v2)
```

Data counts work out!
```{r antijoin v2s, warning=FALSE, message=FALSE}
anti_join(v2_5parties, grace_v2)
```
ALL MATCH!! WOOT!!

V3: TESTING THE R-VERSION COMPARED TO ORIGINAL VERSION
Loading R-version

```{r create r v3}
v3_deduped <- v2_5parties %>%
  distinct(url, text, .keep_all = TRUE)

v3_deduped %>%
  count(publisher.site) %>%
  kable(caption = "All Claims in 5 Parties
        Sorted by Publisher")

dim(v3_deduped)
```

Loading Grace version
```{r load grace v3, warning=FALSE, message=FALSE}
grace_v3 <- read_csv("grace_v3_deduped_CSVversion.csv")

grace_v3 %>%
  count(publisher.site) %>%
  kable(caption = "All Claims in 5 Parties
        Sorted by Publisher")

dim(grace_v3)
```

Data Counts are not the same: why?

```{r antijoin v3s, warning=FALSE, message=FALSE}
anti_join(v3_deduped, grace_v3)
```

```{r table of dupes, warning=FALSE, message=FALSE}
identified_dupes <- anti_join(v2_5parties, v3_deduped)

dim(identified_dupes)
```

LOADING V4 -- Manual removal by ASA

```{r load gracev4, warning=FALSE, message=FALSE}
grace_v4 <- read_csv("grace_V4_dejunkedCSVversion.csv")
```


```{r identifying manual removal, warning=FALSE, message=FALSE}
manual_removes <- anti_join(v3_deduped, grace_v4)
print(manual_removes)
```

MANUALLY CREATING V5

```{r manual removal for v4}
v4_dejunked <- v3_deduped %>%
  filter(claimant != "Donald Trump For Prison") %>%
  filter(claimant !=  "Lauren Boebert; Rudy Giuliani") %>%
  filter(claimant != "Rick Scott's Starbuck's heckler") %>%
  filter(claimant != "Americans United for Change") %>%
  filter(claimant !=  "Consumers for Smart Solar") %>%
  filter(claimant !=  "Greg Gianforte's campaign") %>%
  filter(claimant !=  "Vietnam Veterans Against John McCain") %>%
  filter(claimant != "President Trump's lawyers") %>%
  filter(claimant !=    "Robin Vos and Scott Fitzgerald") %>%
  filter(claimant !=  "Robin Vos; Scott Fitzgerald") %>%
  filter(claimant !=  "Donald Trump 2020 Voters") %>%
  filter(claimant !=  "Michael Bloomberg; Joe Biden; Hillary Clinton; Adam Schiff") %>%
  filter(claimant !=  "Donald Trump and Mike Pence") %>%
  filter(claimant !=  "Bill DeBlasio and Brian Kemp") %>%
  filter(claimant !=  "John Roberts; Fox News correspondent") %>%
  filter(claimant !=  "The Trump campaign") %>%
  filter(claimant !=  "Sen. Ted Cruz (R-Texas) and Rep. Mark Meadows (R-N.C.)") %>%
  filter(claimant !=  "Keith Ellison spokesman") %>%
  filter(claimant !=  "Donald Trump ad") %>%
  filter(claimant !=  "Kamala Harris for the People") %>%
  filter(claimant !=  "Don Bolduc campaign") %>%
  filter(claimant !=  "Donald Trump campaign") %>%
  filter(claimant !=  "Joe Biden campaign") 

```

CREATING V5 code

```{r}
v5_pf <- v4_dejunked %>%
  filter(publisher.site == "politifact.com")

v5_wapo <- v4_dejunked %>%
  filter(publisher.site == "washingtonpost.com")

v5_fc <- v4_dejunked %>%
  filter(publisher.site == "factcheck.org")

v5_nyt <- v4_dejunked %>%
  filter(publisher.site == "nytimes.com")
```

V6: step 1 Testing for Trumps

```{r}
elim_trump <- v4_dejunked %>%
  filter(publisher.site == "politifact.com" |
           publisher.site ==  "washingtonpost.com" |
           publisher.site == "factcheck.org" |
           publisher.site == "nytimes.com")

elim_trump %>%
  filter(grepl('Trump|trump', claimant)) %>%
  group_by(claimant) %>%
  count()
```

