---
title: "PolitiFact Analysis"
author: "Sofia Bliss-Carrascoas"
date: "9/28/2022"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: inline
---

```{r load packages, warning=FALSE, message=FALSE, echo = FALSE}
library(tidyverse)
library(knitr)
library(tibble)
```

```{r color scale and ordering, warning=FALSE, message=FALSE, echo = FALSE }
pf_mega <- read_csv("pf_mega_location.csv")

truenesscolors = c("#FF0000", "#FF872C", "#FAB733", "#FDE64B", "#ACB334", "#69B34C")

pf_mega$textualRating <- factor(pf_mega$textualRating, 
                              levels = c("Pants on Fire", 
                                         "False", 
                                         "Mostly False", 
                                         "Half True", 
                                         "Mostly True", 
                                         "True"))
```

```{r fix tagging error,  warning=FALSE, message=FALSE, echo = FALSE}
pf_mega$`Government Operations`[pf_mega$...1 == "3990"] <- "TRUE"
```

```{r plot of party counts,  warning=FALSE, message=FALSE, echo = FALSE}
ggplot(pf_mega, aes(x = textualRating, fill = claimant_party)) +
 geom_bar(position = "fill") +
  scale_fill_manual( values = c("blue2", "red3")) +
  labs(title = "Ratings Proportions by Party",
       x = "Rating",
       y = "Proportion",
       fill = "Party of Claimant")

ggplot(pf_mega, aes(x = textualRating, fill = claimant_party)) +
 geom_bar() +
  scale_fill_manual(values = c("blue2", "red3")) +
  labs(title = "Ratings Counts by Party",
       x = "Rating",
       y = "Total Claims",
       fill = "Party of Claimant")
```

```{r severity graph,  warning=FALSE, message=FALSE, echo = FALSE}
ggplot(pf_mega, aes(x = claimant_party, fill = textualRating)) +
         geom_bar(position = "fill") +
  labs(title = "Percentage Rating by Party",
       x = "Claims by Party",
       fill = "Rating", y = "Percentage") +
  scale_fill_manual(values = truenesscolors)

dems <- pf_mega %>%
  filter(claimant_party == "Democratic")
dems %>%
  group_by(textualRating) %>%
  count() %>%
  summarize(prop = n/nrow(dems)) %>%
  kable(digits = 4, caption = "Proportion of Democratic Truthfulness")

reps <- pf_mega %>%
  filter(claimant_party == "Republican")
reps %>%
  group_by(textualRating) %>%
  count() %>%
  summarize(prop = n/nrow(dems)) %>%
  kable(digits = 4, caption = "Proportion of Republican Truthfulness")
```

```{r pivot table,  warning=FALSE, message=FALSE, echo = FALSE}
pf_mega %>%
  count(claimant_party, textualRating) %>%
    pivot_wider(id_cols = c(claimant_party),
              names_from = textualRating,
              values_from = n,
              values_fill = 0) %>%
  kable(caption = "Fact-checks per rating by Party")

```

```{r, subject tag table macro,  warning=FALSE, message=FALSE, echo = FALSE}
binarymacro <- pf_mega %>%
  mutate(Fear = case_when(Fear == TRUE ~ 1,
         Fear == FALSE ~ 0)) %>%
  mutate(Legislation = case_when(Legislation == TRUE ~ 1,
         Legislation == FALSE ~ 0)) %>%
  mutate(`Self/Personal Record` = case_when(`Self/Personal Record` == TRUE ~ 1, 
         `Self/Personal Record` == FALSE ~ 0)) %>%
  mutate(`Opponent/Opponent's Record` = 
          case_when(`Opponent/Opponent's Record` == TRUE ~ 1, 
         `Opponent/Opponent's Record` == FALSE ~ 0)) %>%
  select(Fear,
         Legislation,
         `Self/Personal Record`,
         `Opponent/Opponent's Record`,
         claimant_party) %>%
  filter(!is.na(Fear)) 

macro_tibble <- binarymacro %>%
  group_by(claimant_party) %>%
  summarize(Fear = sum(Fear),
            Legislation = sum(Legislation),
            `Self/Personal Record` = sum(`Self/Personal Record`),
            `Opponent/Opponent's Record` = sum(`Opponent/Opponent's Record`))

macro_tibble <- t(macro_tibble)

macro_tibble <- janitor::row_to_names(macro_tibble, 1) 

macro_tibble <- base::data.frame(macro_tibble)

 macro_tibble <- macro_tibble %>% 
  mutate(Democratic = as.numeric(Democratic),
         Republican = as.numeric(Republican))

macro_tibble <- macro_tibble %>%
   mutate(Total = rowSums(across(where(is.numeric))))
macro_tibble %>% kable()

```

```{r subject tag table micro, message= FALSE, warning= FALSE, echo= FALSE }
binarymicro <- pf_mega %>%
  mutate(`National and State Macroeconomic Issues` = 
          case_when(`National and State Macroeconomic Issues` == TRUE ~ 1,
          `National and State Macroeconomic Issues` == FALSE ~ 0)) %>%
  mutate(`Economic Well-Being and Domestic Commerce` = 
          case_when(`Economic Well-Being and Domestic Commerce` == TRUE ~ 1,
         `Economic Well-Being and Domestic Commerce` == FALSE ~ 0)) %>%
   mutate(`Labor and Employment` = case_when(`Labor and Employment` == TRUE ~ 1,
          `Labor and Employment` == FALSE ~ 0)) %>%
   mutate(`Foreign Trade` = case_when(`Foreign Trade` == TRUE ~ 1,
          `Foreign Trade` == FALSE ~ 0)) %>%
   mutate(`Taxes` = case_when(`Taxes` == TRUE ~ 1,
          `Taxes` == FALSE ~ 0)) %>%
   mutate(`Civil Rights, Minority Issues, and Civil Liberties` = 
          case_when(`Civil Rights, Minority Issues, and Civil Liberties` == TRUE ~ 1,
          `Civil Rights, Minority Issues, and Civil Liberties` == FALSE ~ 0)) %>%
   mutate(`Immigration and Refugee Issues` = 
          case_when(`Immigration and Refugee Issues` == TRUE ~ 1,
          `Immigration and Refugee Issues` == FALSE ~ 0)) %>%
   mutate(`LGBTQ` = case_when(`LGBTQ` == TRUE ~ 1,
          `LGBTQ` == FALSE ~ 0)) %>% 
   mutate(`Race` = case_when(`Race` == TRUE ~ 1,
          `Race` == FALSE ~ 0)) %>%
   mutate(`Religion` = case_when(`Religion` == TRUE ~ 1,
          `Religion` == FALSE ~ 0)) %>%
   mutate(`Women` = case_when(`Women` == TRUE ~ 1,
          `Women` == FALSE ~ 0)) %>%
   mutate(`Health (non-care)` = case_when(`Health (non-care)` == TRUE ~ 1,
          `Health (non-care)` == FALSE ~ 0)) %>%
   mutate(`Social Welfare` = case_when(`Social Welfare` == TRUE ~ 1,
          `Social Welfare` == FALSE ~ 0)) %>%
   mutate(`Education` = case_when(`Education` == TRUE ~ 1,
          `Education` == FALSE ~ 0)) %>%
   mutate(`Abortion` = case_when(`Abortion` == TRUE ~ 1,
          `Abortion` == FALSE ~ 0)) %>%
   mutate(`Healthcare` = case_when(`Healthcare` == TRUE ~ 1,
          `Healthcare` == FALSE ~ 0)) %>%
   mutate(`Government Operations` = case_when(`Government Operations` == TRUE ~ 1,
          `Government Operations` == FALSE ~ 0)) %>%
   mutate(`Defense/Military` = case_when(`Defense/Military` == TRUE ~ 1,
          `Defense/Military` == FALSE ~ 0)) %>%
   mutate(`International_affairs and Foreign Aid` = 
           case_when(`International_affairs and Foreign Aid` == TRUE ~ 1,
          `International_affairs and Foreign Aid` == FALSE ~ 0)) %>%
   mutate(`Voting/Elections` = case_when(`Voting/Elections` == TRUE ~ 1,
          `Voting/Elections` == FALSE ~ 0)) %>%
   mutate(`Agriculture` = case_when(`Agriculture` == TRUE ~ 1,
          `Agriculture` == FALSE ~ 0)) %>%
   mutate(`Environment` = case_when(`Environment` == TRUE ~ 1,
          `Environment` == FALSE ~ 0)) %>%
   mutate(`Energy` = case_when(`Energy` == TRUE ~ 1,
          `Energy` == FALSE ~ 0)) %>%
   mutate(`Transportation` = case_when(`Transportation` == TRUE ~ 1,
          `Transportation` == FALSE ~ 0)) %>%
   mutate(`Community Development and Housing` = 
           case_when(`Community Development and Housing` == TRUE ~ 1,
          `Community Development and Housing` == FALSE ~ 0)) %>%
   mutate(`Technology Science Space` = 
           case_when(`Technology Science Space` == TRUE ~ 1,
          `Technology Science Space` == FALSE ~ 0)) %>%
   mutate(`Media and Communications` = 
           case_when(`Media and Communications` == TRUE ~ 1,
          `Media and Communications` == FALSE ~ 0)) %>%
   mutate(`Law and Crime and Policing` = 
           case_when(`Law and Crime and Policing` == TRUE ~ 1,
          `Law and Crime and Policing` == FALSE ~ 0)) %>%
   mutate(`Terrorism` = case_when(`Terrorism` == TRUE ~ 1,
          `Terrorism` == FALSE ~ 0)) %>%
   mutate(`Guns` = case_when(`Guns` == TRUE ~ 1,
          `Guns` == FALSE ~ 0)) %>%
   mutate(`History` = case_when(`History` == TRUE ~ 1,
          `History` == FALSE ~ 0)) %>%
   mutate(`Record/Candidate Biography/ Campaigns and Personal Behavior` = 
      case_when(`Record/Candidate Biography/ Campaigns and Personal Behavior` == TRUE ~ 1,
          `Record/Candidate Biography/ Campaigns and Personal Behavior` == FALSE ~ 0)) %>%
  select(`National and State Macroeconomic Issues`,
         `Economic Well-Being and Domestic Commerce`,
         `Labor and Employment`,
         `Foreign Trade`,
         `Civil Rights, Minority Issues, and Civil Liberties`,
         `Immigration and Refugee Issues`,
         `LGBTQ`,
         `Race`,
         `Taxes`,
         `Religion`,
         `Women`,
         `Health (non-care)`,
         `Social Welfare`,
         `Education`,
         `Abortion`,
         `Healthcare`,
         `Government Operations`,
         `Defense/Military`,
         `International_affairs and Foreign Aid`,
         `Voting/Elections`,
         `Agriculture`,
         `Environment`,
         `Energy`,
         `Transportation`,
         `Community Development and Housing`,
         `Technology Science Space`,
         `Media and Communications`,
         `Law and Crime and Policing`,
         `Terrorism`,
         `Guns`,
         `History`,
         `Record/Candidate Biography/ Campaigns and Personal Behavior`,
          claimant_party) %>%
  filter(!is.na(`Foreign Trade`)) 

micro_tibble <- binarymicro %>%
  group_by(claimant_party) %>%
  summarize( `National and State Macroeconomic Issues` = 
              sum(`National and State Macroeconomic Issues`),
             `Economic Well-Being and Domestic Commerce` = 
              sum(`Economic Well-Being and Domestic Commerce`),
             `Labor and Employment` = sum(`Labor and Employment`),
             `Foreign Trade` = sum(`Foreign Trade`),
             `Civil Rights, Minority Issues, and Civil Liberties` =
              sum(`Civil Rights, Minority Issues, and Civil Liberties`),
             `Immigration and Refugee Issues` = sum(`Immigration and Refugee Issues`),
             `LGBTQ` = sum(`LGBTQ`),
             `Race` = sum(`Race`),
             `Religion` = sum(`Religion`),
             `Women` = sum(`Women`),
             `Health (non-care)` = sum(`Health (non-care)`),
             `Social Welfare` = sum(`Social Welfare`),
             `Education` = sum(`Education`),
             `Abortion` = sum(`Abortion`),
             `Healthcare` = sum(`Healthcare`),
             `Government Operations` = sum(`Government Operations`),
             `Defense/Military` = sum(`Defense/Military`),
             `International_affairs and Foreign Aid` =
              sum(`International_affairs and Foreign Aid`),
             `Voting/Elections` = sum(`Voting/Elections`),
             `Agriculture` = sum(`Agriculture`),
             `Environment` = sum(`Environment`),
             `Energy` = sum(`Energy`),
             `Transportation` = sum(`Transportation`),
              `Taxes` = sum(`Taxes`),
             `Community Development and Housing` = 
              sum(`Community Development and Housing`),
             `Technology Science Space` = sum(`Technology Science Space`),
             `Media and Communications` = sum(`Media and Communications`),
             `Law and Crime and Policing` = sum(`Law and Crime and Policing`),
             `Terrorism` = sum(`Terrorism`),
             `Guns` = sum(`Guns`),
             `History` = sum(`History`),
             `Record/Candidate Biography/ Campaigns and Personal Behavior` =
              sum(`Record/Candidate Biography/ Campaigns and Personal Behavior`))

micro_tibble <- t(micro_tibble)

micro_tibble <- janitor::row_to_names(micro_tibble, 1) 

micro_tibble <- base::data.frame(micro_tibble)

micro_tibble <- micro_tibble %>% 
  mutate(Democratic = as.numeric(Democratic),
         Republican = as.numeric(Republican))

micro_tibble <- micro_tibble %>%
   mutate(Total = rowSums(across(where(is.numeric))))

micro_tibble %>% kable()
```





