---
title: "PolitiFact Analysis"
author: "Grace Abels"
date: "4/19/2022"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r load packages, warning=FALSE, message=FALSE, echo = FALSE}
library(tidyverse)
library(knitr)
```

```{r}
v8_pf <- read_csv("v8pf.csv")
```

```{r orig text ratings, warning=FALSE, message=FALSE, echo = FALSE}
v8_pf %>%
  group_by(textualRating) %>%
  count() %>%
  arrange(desc(n)) %>%
  kable(caption = "Textual Ratings")
```

```{r use pF ratings, warning=FALSE, message=FALSE, echo = FALSE}
v9_pf <- v8_pf %>%
  filter(textualRating == "TRUE" |
           textualRating == "Mostly True" |
           textualRating == "Half True" |
           textualRating == "Mostly False" |
           textualRating == "FALSE" |
           textualRating == "Pants on Fire" )

v9_pf <- v9_pf %>%
  mutate(textualRating = case_when(textualRating == "TRUE" ~ "True",
                   textualRating == "FALSE" ~ "False",
                   textualRating == "Mostly True" ~ "Mostly True",
                   textualRating == "Half True" ~ "Half True",
                   textualRating == "Mostly False" ~ "Mostly False",
                   textualRating == "Pants on Fire" ~ "Pants on Fire"))

v9_pf$textualRating <- factor(v9_pf$textualRating, 
                              levels = c("Pants on Fire", 
                                         "False", 
                                         "Mostly False", 
                                         "Half True", 
                                         "Mostly True", 
                                         "True"))

v9_pf %>%
  group_by(textualRating) %>%
  count() %>%
  kable(caption = "PF Claims with Truth-O-Meter Ratings")
```


