---
title: "Washington Post"
author: "Sofia Bliss-Carrascosa"
date: "10/05/2022"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r load packages, warning=FALSE, message=FALSE, echo = FALSE}
library(tidyverse)
library(knitr)
```

```{r, warning=FALSE, message=FALSE, echo = FALSE}
v8_wapo <- read.csv("v8wapo-cleantextrating.csv")

v8_wapo_cleantextRating <- v8_wapo %>%
  filter(textualRating == "One Pinocchio" |
           textualRating == "Two Pinocchios" |
           textualRating == "Three Pinocchios" |
           textualRating == "Four Pinocchios" |
           textualRating == "Geppetto Checkmark" |
           textualRating == "Needs context" |
           textualRating == "Disputed" |
           textualRating == "Misleading" |
           textualRating == "No evidence" |
           textualRating == "Lacks evidence" |
           textualRating == "Study in Dispute")


v8_wapo_cleantextRating$textualRating <- factor(v8_wapo_cleantextRating$textualRating, 
                              levels = c("Geppetto Checkmark", 
                                         "One Pinocchio", 
                                         "Two Pinocchios", 
                                         "Three Pinocchios", 
                                         "Four Pinocchios", 
                                         "Disputed",
                                         "Study in Dispute",
                                         "Misleading",
                                         "Needs context",
                                         "Lacks evidence",
                                         "No evidence"))
```

```{r, warning=FALSE, message=FALSE, echo = FALSE}
v8_wapo_cleantextRating %>%
  group_by(claimant_party) %>%
  count() %>%
  kable(caption = "Claim Counts by Party")

v8_wapo_cleantextRating %>%
  group_by(textualRating) %>%
  count() %>%
  kable(caption = "Claim Counts by Rating")

v8_wapo_cleantextRating %>%
  group_by(claimant_party, textualRating) %>%
  count() %>%
  pivot_wider(id_cols = claimant_party, 
              names_from = textualRating, 
              values_from = n,
              values_fill = 0) %>%
  kable(caption = "Claim Counts by Party and Rating")
```

```{r, warning=FALSE, message=FALSE, echo = FALSE}
v8_wapo_5scale <- v8_wapo_cleantextRating %>%
  filter(textualRating == "One Pinocchio" |
           textualRating == "Two Pinocchios" |
           textualRating == "Three Pinocchios" |
           textualRating == "Four Pinocchios" |
           textualRating == "Geppetto Checkmark")

v8_wapo_5scale %>%
  ggplot(aes(x = textualRating, fill = claimant_party)) +
  geom_bar(position = "fill") +
  scale_fill_manual( values = c("blue2", "red3")) +
  labs(title = "Rating Proportions by Party",
       x = "Rating",
       y = "Proportion",
       fill = "Party of Claimant")

v8_wapo_5scale %>%
  ggplot(aes(x = textualRating, fill = claimant_party)) +
  geom_bar() +
  scale_fill_manual( values = c("blue2", "red3")) +
  labs(title = "Rating Counts by Party",
       x = "Rating",
       y = "Counts",
       fill = "Party of Claimant")
```


